### ISSUE TITLE
Crash when aborting game during game startup.

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#109]
1. New Game
2. Abort Game (while startup)
3. Caused by: java.lang.NullPointerException
   at org.jtrfp.trcl.obj.Player.<init>(Player.java:83)
   at org.jtrfp.trcl.flow.Game.boot(Game.java:318)
   at org.jtrfp.trcl.flow.GameShell.newGame(GameShell.java:129)
4. TRCL exits

**Comment by cjritola** [comment]
Issue no longer manifests.
