### ISSUE TITLE
NegativeTallyException during gameplay

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#133]
Exception in thread "pool-195-thread-2" org.jtrfp.trcl.coll.ObjectTallyCollection$NegativeTallyException
    at org.jtrfp.trcl.coll.ObjectTallyCollection.decrement(ObjectTallyCollection.java:58)
    at org.jtrfp.trcl.coll.ObjectTallyCollection.remove(ObjectTallyCollection.java:122)
    at org.jtrfp.trcl.tools.Util.bulkRemove(Util.java:363)
    at org.jtrfp.trcl.coll.CollectionThreadDecoupler$8.run(CollectionThreadDecoupler.java:156)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:701)

The ObjectTallyCollection in RendererFactory currently used to track relevant portal entrances is catching a imbalance between released portals and acquired portals, implying some sort of redundant release further up the relevance calculation chain, outside of what can be given in the stacktrace due to thread decoupling.

**Comment by cjritola** [comment]
Unable to produce.
