### ISSUE TITLE
NPE on startup

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#141]
```
java.lang.NullPointerException
    at org.jtrfp.trcl.gpu.Model$1.call(Model.java:164)
    at org.jtrfp.trcl.gpu.Model$1.call(Model.java:1)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at org.jtrfp.trcl.core.TRFutureTask.run(TRFutureTask.java:40)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:701)
```

**Comment by cjritola** [comment]
Issue no longer manifests.
