### ISSUE TITLE
Exception when skipping level

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#154]
Game crashes with exception when using level-skip during gameplay.

> java.lang.RuntimeException: java.lang.IllegalArgumentException: Cannot find subnode Pause inside of submenu Game
> 	at org.jtrfp.trcl.shell.GameShellFactory$GameShell.handleLoadFailureException(GameShellFactory.java:290)
> 	at org.jtrfp.trcl.shell.GameShellFactory$GameShell.gameFailure(GameShellFactory.java:259)
> 	at org.jtrfp.trcl.shell.GameShellFactory$GameShell.startGame(GameShellFactory.java:254)
> 	at org.jtrfp.trcl.shell.GameShellFactory$GameShell$StartGameMenuItemListener$1.call(GameShellFactory.java:129)
> 	at org.jtrfp.trcl.shell.GameShellFactory$GameShell$StartGameMenuItemListener$1.call(GameShellFactory.java:1)
> 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
> 	at org.jtrfp.trcl.core.TRFutureTask.run(TRFutureTask.java:40)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
> 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:701)
> Caused by: java.lang.IllegalArgumentException: Cannot find subnode Pause inside of submenu Game
> 	at org.jtrfp.trcl.gui.SwingMenuSystemFactory$SwingMenuSystem$SubMenu.setMenuItemEnabled(SwingMenuSystemFactory.java:480)
> 	at org.jtrfp.trcl.gui.SwingMenuSystemFactory$SwingMenuSystem$SubMenu.setMenuItemEnabled(SwingMenuSystemFactory.java:478)
> 	at org.jtrfp.trcl.gui.SwingMenuSystemFactory$SwingMenuSystem.setMenuItemEnabled(SwingMenuSystemFactory.java:355)
> 	at org.jtrfp.trcl.miss.GamePauseFactory$GamePause$RunStateListener.propertyChange(GamePauseFactory.java:97)
> 	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:298)
> 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:292)
> 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:229)
> 	at org.jtrfp.trcl.core.TRFactory$TR.setRunState(TRFactory.java:541)
> 	at org.jtrfp.trcl.game.TVF3Game.doGameplay(TVF3Game.java:407)
> 	at org.jtrfp.trcl.shell.GameShellFactory$GameShell.startGame(GameShellFactory.java:250)
> 	... 11 more
> 
> Irrecoverable. Exiting...

**Comment by cjritola** [comment]
Unable to recreate issue; may have been fixed by bbbe8dd.
