### ISSUE TITLE
State errors when skip-to-level induced from satellite view.

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#169]
When in satellite view, skip-to-level causes satellite overlay to hang in the scene, causing rendering errors later in gameplay.

**Comment by cjritola** [comment]
Possibly related exception when this happens:
java.lang.IllegalStateException: Passed element WorldObject([unnamed]) Model=ViewSelect.NavRadarBlipFactory pos=[D@4e0a4151 class=org.jtrfp.trcl.obj.NAVRadarBlipFactory$Blip hash=387291258 has non-null containing grid: org.jtrfp.trcl.RenderableSpacePartitioningGrid@24a1de60. Object should only be in one grid at a time.
	at org.jtrfp.trcl.SpacePartitioningGrid.addAll(SpacePartitioningGrid.java:113)
	at org.jtrfp.trcl.obj.NAVRadarBlipFactory.enableNewBlips(NAVRadarBlipFactory.java:252)
	at org.jtrfp.trcl.obj.NAVRadarBlipFactory.refreshBlips(NAVRadarBlipFactory.java:245)
	at org.jtrfp.trcl.obj.NAVRadarBlipFactory.refreshBlips(NAVRadarBlipFactory.java:248)
	at org.jtrfp.trcl.beh.UpdatesNAVRadar.tick(UpdatesNAVRadar.java:47)
	at org.jtrfp.trcl.beh.Behavior.proposeTick(Behavior.java:29)
	at org.jtrfp.trcl.obj.WorldObject.tick(WorldObject.java:231)
	at org.jtrfp.trcl.core.ThreadManager.gameplay(ThreadManager.java:139)
	at org.jtrfp.trcl.core.ThreadManager.access$3(ThreadManager.java:114)
	at org.jtrfp.trcl.core.ThreadManager$5.run(ThreadManager.java:201)
	at java.util.TimerThread.mainLoop(Timer.java:534)
	at java.util.TimerThread.run(Timer.java:484)
