### ISSUE TITLE
End briefing for ASTROID3.LVL throws FileNotFoundException due to null.raw

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#204]
End briefing for LAVA throws NPE due to null.raw

**Comment by WDLmaster** [comment]
Very interesting that you mention the LAVA map(s) because there is a known bug, found ONLY in those maps and nowhere else in TV/F3 (developers acknowledged it even back in 1995) that causes the original game to crash in roughly 50% of cases after exiting a certain tunnel. Coincidence? Very possible that both games (TR and TV) crash for the same reasons in that case.

**Comment by cjritola** [comment]
Glad you mentioned that; I'm going to look further into it.

**Comment by cjritola** [comment]
Good news: Attempted to invoke the LAVA right-tunnel crash in TRCL and it worked fine. The differences in tunnel handling between the engines probably helped.
Bad news: I specified the wrong level name. It is actually ASTROID3.LVL and the issue persists. It is mostly benign, printing to log but continuing.

`setRunState org.jtrfp.trcl.miss.Mission$8@3bb9eb07 old=org.jtrfp.trcl.miss.WarpEscapeFactory$WarpEscape$1@5e9c0ec0
Getting resource: DATA\astroid.txt
Getting resource: ART\null.raw
java.io.FileNotFoundException: ART\null.raw
Getting resource: MODELS\stroid.bin
	at org.jtrfp.trcl.core.ResourceManager.getInputStreamFromResource(ResourceManager.java:246)
	at org.jtrfp.trcl.core.ResourceManager.getRAW(ResourceManager.java:605)
	at org.jtrfp.trcl.core.ResourceManager.getRAWVectorList(ResourceManager.java:648)
	at org.jtrfp.trcl.core.ResourceManager.getRAWAsTexture(ResourceManager.java:327)
	at org.jtrfp.trcl.core.ResourceManager.getRAWAsTexture(ResourceManager.java:293)
	at org.jtrfp.trcl.BriefingScreen.planetDisplayMode(BriefingScreen.java:161)
	at org.jtrfp.trcl.BriefingScreen.missionCompleteSummary(BriefingScreen.java:203)
	at org.jtrfp.trcl.miss.Mission.go(Mission.java:462)
	at org.jtrfp.trcl.game.TVF3Game.doGameplay(TVF3Game.java:398)
	at org.jtrfp.trcl.gui.LevelSkipWindow$3$1.call(LevelSkipWindow.java:147)
	at org.jtrfp.trcl.gui.LevelSkipWindow$3$1.call(LevelSkipWindow.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.jtrfp.trcl.core.TRFutureTask.run(TRFutureTask.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Recognized as model file.
Failed to identify DataBlock: org.jtrfp.trcl.file.BINFile$Model$DataBlock$Unknown17
ResourceManager: TextureBlock specifies texture: STROIDGI.RAW`
