### ISSUE TITLE
Exception when loading state with an exited tunnel objective

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#211]
Hanging XIT objective when loading a saved game state which has exited tunnel, resulting in Exception:

> Unrecognized NAV objective: org.jtrfp.trcl.file.NAVFile$START@51cd29d5 
java.lang.NullPointerException 
    at org.jtrfp.trcl.miss.NAVObjective$Factory.create(NAVObjective.java:346) 
    at org.jtrfp.trcl.miss.Mission.go(Mission.java:313) 
    at org.jtrfp.trcl.game.TVF3Game.doGameplay(TVF3Game.java:398) 
    at org.jtrfp.trcl.game.GamestateSaveLoadDialogSystem.load(GamestateSaveLoadDialogSystem.java:76) 
    at org.jtrfp.trcl.game.GamestateSaveLoadMenuItemFactory$GameSaveLoadMenuItemFeature$LoadGameMenuItemListener$1.run(GamestateSaveLoadMenuItemFactory.java:104) 
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
    at java.lang.Thread.run(Thread.java:745) 

Reported by Roy Hepner.

**Comment by cjritola** [comment]
On further examination this is not a race condition. The savestate is saving XIT objectives without preceeding TUN objectives. As a result the Mission loader is confused as there is no tunnel defined to exit from.
To produce:
1. Load a level which has a tunnel as part of the objectives (ATMOS2.LVL)
2. Proceed through the NAVs until exiting from the tunnel.
3. Save the state after exiting the tunnel
4. Load the state.
5. NPE due to hanging XIT objective.

**Comment by cjritola** [comment]
Work underway to add tolerance of bad savestate so it can be used in the meantime. Standby.

**Comment by cjritola** [comment]
It should now be possible to load the bad savestate and continue without a crash.
