### ISSUE TITLE
Abort game... new game greyed out after gameplay. Start game crash

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#214]
Steps:
1. Start F3/TV game, play first level
2. Select Game->Abort
3. New TV/F3 Game greyed out
3. Start new game
4. Crash

> ==== SHOWSTOPPER ====
java.lang.RuntimeException: java.lang.NullPointerException
	at org.jtrfp.trcl.shell.GameShellFactory$GameShell.handleLoadFailureException(GameShellFactory.java:285)
	at org.jtrfp.trcl.shell.GameShellFactory$GameShell.gameFailure(GameShellFactory.java:254)
	at org.jtrfp.trcl.shell.GameShellFactory$GameShell.startGame(GameShellFactory.java:249)
	at org.jtrfp.trcl.shell.GameShellFactory$GameShell$StartGameMenuItemListener$1.call(GameShellFactory.java:121)
	at org.jtrfp.trcl.shell.GameShellFactory$GameShell$StartGameMenuItemListener$1.call(GameShellFactory.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.jtrfp.trcl.core.TRFutureTask.run(TRFutureTask.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.jtrfp.trcl.shell.GameShellFactory$GameShell.startGame(GameShellFactory.java:245)
	... 9 more

**Comment by cjritola** [comment]
Issue not longer manifests.
