### ISSUE TITLE
Exception when exiting tunnel (1in20)

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#221]
> Exiting tunnel:
    Exception in thread "Transient Thread-FPSAWTAnimator-Timer0" java.lang.RuntimeException: java.lang.AssertionError
	at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
	at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:100)
	at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:205)
	at javax.media.opengl.Threading.invokeOnOpenGLThread(Threading.java:172)
	at javax.media.opengl.Threading.invoke(Threading.java:191)
	at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:483)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:74)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:440)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:167)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.AssertionError
	at org.jtrfp.trcl.math.Vect3D.checkValues(Vect3D.java:60)
	at org.jtrfp.trcl.math.Vect3D.norm(Vect3D.java:106)
	at org.jtrfp.trcl.math.Vect3D.normalize(Vect3D.java:91)
	at org.jtrfp.trcl.obj.WorldObject.recalculateTransRotMBuffer(WorldObject.java:453)
	at org.jtrfp.trcl.obj.WorldObject.updateStateToGPU(WorldObject.java:391)
	at org.jtrfp.trcl.gpu.Renderer.updateStatesToGPU(Renderer.java:413)
	at org.jtrfp.trcl.gpu.Renderer.sendToGPU(Renderer.java:453)
	at org.jtrfp.trcl.gpu.Renderer$2.call(Renderer.java:248)
	at org.jtrfp.trcl.gpu.Renderer$2.call(Renderer.java:1)
	at org.jtrfp.trcl.core.ThreadManager.attemptRender(ThreadManager.java:266)
	at org.jtrfp.trcl.core.ThreadManager.access$8(ThreadManager.java:250)
	at org.jtrfp.trcl.core.ThreadManager$7.display(ThreadManager.java:237)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:588)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:572)
	at javax.media.opengl.awt.GLCanvas$7.run(GLCanvas.java:1054)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1034)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:909)
	at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:1065)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by cjritola** [comment]
Issue no longer manifests.
