### ISSUE TITLE
ExceptionInInitializerError when running from Java 16.

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#274]
```
Exception in thread "Transient Thread" java.lang.IllegalStateException: Cannot load configuration class: org.jtrfp.trcl.flow.RunMe
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:410)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:263)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:130)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:674)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:519)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at org.jtrfp.trcl.flow.RunMe$1.run(RunMe.java:67)
	at org.jtrfp.trcl.core.DefaultKeyedExecutor.executeAllFromThisThread(DefaultKeyedExecutor.java:64)
	at org.jtrfp.trcl.flow.TransientExecutor$TransientThread.run(TransientExecutor.java:43)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(Unknown Source)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(Unknown Source)
	at org.springframework.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:166)
	at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at org.springframework.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144)
	at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:116)
	at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:108)
	at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:104)
	at org.springframework.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
	at org.springframework.context.annotation.ConfigurationClassEnhancer.newEnhancer(ConfigurationClassEnhancer.java:121)
	at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:109)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:400)
	... 9 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @559be735
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
	at org.springframework.cglib.core.ReflectUtils$2.run(ReflectUtils.java:56)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.springframework.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:46)
	... 20 more
```

Looks like Spring version needs to be bumped up.

**Comment by cjritola** [comment]
Probably related to #272
