### ISSUE TITLE
fails to start with both openjdk 11 and 17 on Debian

### ISSUE THREAD

**Issue by wsourdeau** [jtrfp/terminal-recall#276]
When starting the game, the following message appears, without any other output, and then the process just stops. I suspect this might be due to a bug in one of its dependencies.

Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

Under gdb, with a breakpoint set on dl-lookup.c:105, I can get the following backtrace:

(gdb) bt
#0  check_match (undef_name=undef_name@entry=0x7fff6b0006d1 "JAWT_GetAWT", ref=ref@entry=0x7fff6b000268, version=version@entry=0x7fff744b9a00, flags=flags@entry=5, 
    type_class=type_class@entry=1, sym=0x7fffc91673e8, symidx=14, strtab=0x7fffc9167430 "", map=0x7fff744b8710, versioned_sym=0x7fffc95f12c8, num_versions=0x7fffc95f12c4)
    at dl-lookup.c:105
#1  0x00007ffff7fd6af4 in do_lookup_x (undef_name=undef_name@entry=0x7fff6b0006d1 "JAWT_GetAWT", new_hash=new_hash@entry=3634921062, 
    old_hash=old_hash@entry=0x7fffc95f1380, ref=0x7fff6b000268, result=result@entry=0x7fffc95f1390, scope=<optimized out>, i=<optimized out>, version=0x7fff744b9a00, 
    flags=5, skip=<optimized out>, type_class=1, undef_map=0x7fff744b8ce0) at dl-lookup.c:430
#2  0x00007ffff7fd7421 in _dl_lookup_symbol_x (undef_name=0x7fff6b0006d1 "JAWT_GetAWT", undef_map=0x7fff744b8ce0, ref=ref@entry=0x7fffc95f1428, 
    symbol_scope=0x7fff744b9050, version=0x7fff744b9a00, type_class=type_class@entry=1, flags=5, skip_map=0x0) at dl-lookup.c:855
#3  0x00007ffff7fdb633 in _dl_fixup (l=<optimized out>, reloc_arg=<optimized out>) at dl-runtime.c:109
#4  0x00007ffff7fe2a4a in _dl_runtime_resolve_xsavec () at ../sysdeps/x86_64/dl-trampoline.h:126
#5  0x00007fff6b000e9f in Java_jogamp_nativewindow_jawt_JAWTFactory_JAWT_1GetAWT1__Ljava_nio_ByteBuffer_2 ()
   from /tmp/jogamp_0000/file_cache/jln5501713894673726142/jln5277187009150532903/natives/linux-amd64/libnativewindow_awt.so
#6  0x00007fffd920d71a in ?? ()
#7  0x0000000000000000 in ?? ()

**Comment by cjritola** [comment]
Known issue, most likely due to JOGL:
https://forum.jogamp.org/Inconsistency-detected-by-ld-so-dl-lookup-c-td4040188.html
Workaround is to use[ Termium JDK](https://adoptium.net/) instead of vanilla OpenJDK.

**Comment by cjritola** [comment]
Most recent commits likely put this issue to rest. Closing...

**Comment by wsourdeau** [comment]
> Most recent commits likely put this issue to rest. Closing...

Indeed. It works well now. Thanks!
