### ISSUE TITLE
CITY.LVL EOFException (nonfatal)

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#36]
Getting resource: DATA\city-t2.def
NewHit not given for this def
NewAttackRet not given for this def
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at org.jtrfp.jfdt.EndianAwareDataInputStream.readFully(EndianAwareDataInputStream.java:106)
	at org.jtrfp.jfdt.Parser$7.read(Parser.java:528)
	at org.jtrfp.jfdt.Parser$RWHelper.go(Parser.java:328)
	at org.jtrfp.jfdt.Parser.expectBytes(Parser.java:521)
	at org.jtrfp.jfdt.Parser.expectString(Parser.java:592)
	at org.jtrfp.trcl.file.DEFFile$EnemyDefinition.describeFormat(DEFFile.java:114)
	at org.jtrfp.jfdt.Parser.readToNewBean(Parser.java:156)
	at org.jtrfp.jfdt.Parser$15.read(Parser.java:1164)
	at org.jtrfp.jfdt.Parser$RWHelper.go(Parser.java:328)
	at org.jtrfp.jfdt.Parser.arrayOf(Parser.java:1152)
	at org.jtrfp.trcl.file.DEFFile.describeFormat(DEFFile.java:46)
	at org.jtrfp.jfdt.Parser.readToExistingBean(Parser.java:100)
	at org.jtrfp.jfdt.Parser.readToExistingBean(Parser.java:84)
	at org.jtrfp.jfdt.SelfParsingFile.<init>(SelfParsingFile.java:29)
	at org.jtrfp.trcl.file.DEFFile.<init>(DEFFile.java:37)
	at org.jtrfp.trcl.core.ResourceManager.getDEFData(ResourceManager.java:497)
	at org.jtrfp.trcl.obj.ObjectSystem.<init>(ObjectSystem.java:38)
	at org.jtrfp.trcl.Tunnel.<init>(Tunnel.java:78)
	at org.jtrfp.trcl.flow.Mission.newTunnel(Mission.java:213)
	at org.jtrfp.trcl.TunnelInstaller.<init>(TunnelInstaller.java:32)
	at org.jtrfp.trcl.flow.Mission$2.call(Mission.java:125)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.jtrfp.trcl.core.ThreadManager$1.display(ThreadManager.java:95)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:588)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:572)
	at javax.media.opengl.awt.GLCanvas$7.run(GLCanvas.java:1054)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1034)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:909)
	at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:1065)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:241)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
... this exception occured while accessing offset 109 (0x6D)

**Comment by cjritola** [comment]
Now getting a fatal crash on this level as well.
