### ISSUE TITLE
Crash at load

### ISSUE THREAD

**Issue by StrikerMan780** [jtrfp/terminal-recall#89]
```
Initializing graphics engine...
Setting up sound system...
...Done
GLEventListener.init()
SoundSystem: Active Driver Set To JavaSound Driver
SoundSystem: Active Device Set To null
setOutputByName null
SoundSystem: Active Output Set To null
Register pod H:\sourcecode\TerminalRecall\terminal-recall\FURY3.POD
SoundSystem: setting up textures...
...Done.
Register pod H:\sourcecode\TerminalRecall\terminal-recall\STARTUP.POD
Register pod H:\sourcecode\TerminalRecall\terminal-recall\CDROM.POD
==== SHOWSTOPPER ====
==== SHOWSTOPPER ====
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at org.jtrfp.trcl.core.TRFutureTask.run(TRFutureTask.java:33)
    at org.jtrfp.trcl.core.GLFutureTask.run(GLFutureTask.java:35)
    at jogamp.opengl.GLRunnableTask.run(GLRunnableTask.java:59)
    at jogamp.opengl.GLDrawableHelper.execGLRunnables(GLDrawableHelper.java:633)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:573)
    at javax.media.opengl.awt.GLCanvas$7.run(GLCanvas.java:1054)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1034)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:909)
    at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:1065)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at org.jtrfp.trcl.snd.SoundSystem.getGPUFloatBytes(SoundSystem.java:657)
    at org.jtrfp.trcl.snd.SoundSystem$3$1.call(SoundSystem.java:133)
    at org.jtrfp.trcl.snd.SoundSystem$3$1.call(SoundSystem.java:130)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    ... 23 more
======================

Irrecoverable. Exiting...


java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at org.jtrfp.trcl.core.TRFutureTask.get(TRFutureTask.java:49)
    at org.jtrfp.trcl.core.GLFutureTask.get(GLFutureTask.java:44)
    at org.jtrfp.trcl.snd.SoundSystem$3.run(SoundSystem.java:130)
Caused by: java.lang.NullPointerException
    at org.jtrfp.trcl.snd.SoundSystem.getGPUFloatBytes(SoundSystem.java:657)
    at org.jtrfp.trcl.snd.SoundSystem$3$1.call(SoundSystem.java:133)
    at org.jtrfp.trcl.snd.SoundSystem$3$1.call(SoundSystem.java:130)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at org.jtrfp.trcl.core.TRFutureTask.run(TRFutureTask.java:33)
    at org.jtrfp.trcl.core.GLFutureTask.run(GLFutureTask.java:35)
    at jogamp.opengl.GLRunnableTask.run(GLRunnableTask.java:59)
    at jogamp.opengl.GLDrawableHelper.execGLRunnables(GLDrawableHelper.java:633)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:573)
    at javax.media.opengl.awt.GLCanvas$7.run(GLCanvas.java:1054)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1034)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:909)
    at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:1065)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
======================

Irrecoverable. Exiting...

```

**Comment by cjritola** [comment]
I'm on it.

**Comment by cjritola** [comment]
Is anyone still getting this issue?

**Comment by WDLmaster** [comment]
Yes, but instead of crashing directly on launch, it now crashes when starting a game (selecting [game] -> [new game] -> [ok] -> [ok] -> a few milliseconds of loading, then crash) 

www.wdlmaster.de/TRCL/log.html

**Comment by cjritola** [comment]
This is going to require a minor redesign which should be ready within a few days.

Explanation: Sound events are being set up before valid sample rates are set. Ideally, the sample rate (and format in general) are unnecessary as it could be implemented in terms of intrinsic playback time instead of sample counts, independent of the audio hardware involved. In this sense, the audio card's playback buffer units would be analogous to window-space coordinates while audio event time units would be analogous to world-space coordinates.
